name: remote ssh command for deploy
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
#  pull_request:
#    branches: [main]
#    paths-ignore:
#      - 'README.md'
#      - 'docs/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ec2-user
          port: 22
          script: |
            ./deploy.sh
